# Generated by Django 2.1.4 on 2018-12-28 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
