# Generated by Django 2.1.5 on 2019-02-03 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20181228_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
